apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-api
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENV
          value: dev
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: VERSION
          value: "1.0.0"
    target:
      kind: Deployment
      name: hello-api
