apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-api-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/walteribanez555/aws-k8
    targetRevision: HEAD
    path: gitops/manifests/hello-api/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
